# Generated by Django 6.0.1 on 2026-01-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='orden_id',
            field=models.CharField(default='s', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
